---
- name: Manage GNS3 devices
  hosts: sw1
  gather_facts: false
  connection: local

  vars:
    cli:
      username: samir
      password: cisco


  tasks:
 
  - name: SET SNMP SERVER ADDRESS 
    ios_config:
      lines:
        - snmp-server host 192.168.161.110 version 2c public udp-port 161
