---
- name: Manage EVE-NG Cisco IOS devices
  hosts: all
  gather_facts: false
  connection: local

  vars:
    cli:
      username: samir
      password: cisco

  tasks:
  - name: SET COMMUNITY STRING 
    ios_config:
      provider: "{{ cli }}"
      authorize: yes
      lines:
        - snmp-server community ansibull RO 99

  - name: TRAP-SOURCE LOOPBACK0 
    ios_config:
      provider: "{{ cli }}"
      authorize: yes
      lines:
         - snmp-server trap-source Loopback0

  - name: SET CONTACT INFO 
    ios_config:
      provider: "{{ cli }}"
      authorize: yes
      lines:
        - snmp-server contact samir.mahboub@gmail.com

  - name: ENABLE OSPF TRAPS 
    ios_config:
      provider: "{{ cli }}"
      authorize: yes
      lines:
        - snmp-server enable traps ospf state-change
        - snmp-server enable traps ospf errors
        - snmp-server enable traps ospf retransmit
        - snmp-server enable traps ospf lsa
        - snmp-server enable traps ospf cisco-specific errors
        - snmp-server enable traps ospf cisco-specific retransmit
        - snmp-server enable traps ospf cisco-specific lsa

  - name: SET SNMP SERVER ADDRESS 
    ios_config:
      provider: "{{ cli }}"
      authorize: yes
      lines:
        - snmp-server host 192.168.1.200 version 2c public udp-port 161
